Set Shell "bash"
Set FontSize 18
Set Theme "Catppuccin Mocha"
Set PlaybackSpeed 4.0
Set Margin 10
Set BorderRadius 10
Set Framerate 60
Set MarginFill "#6B50FF"
Set WindowBar Colorful
Set Width 1200
Set Height 780
Env VHS_NO_SANDBOX "1"
Output assets/demo.gif
Hide
Type "export PS1='\$ '"
Enter
Type "clear"
Enter
Show


Type "uv run cafe-scout"
Enter
Sleep 4s
Down
Down
Down
Enter
Sleep 20s
Enter
Sleep 4s
Type "py"
Down
Down
Enter
Sleep 4s
Ctrl+W
Type "postg"
Down
Down
Enter
Sleep 4s
Up
Enter
Sleep 4s
Down
Down
Enter
Sleep 4s
Type "React"
Sleep 4s
Enter
Sleep 4s
Down
Down
Down
Enter
Sleep 4s
Down
Down
Enter
Sleep 4s
Down
Down
Enter
Sleep 4s
Down
Enter
Sleep 4s
Up
Enter
Sleep 4s
Down
Down
Down
Enter
Sleep 4s
Down
Down
Down
Down
Enter
Sleep 4s
Ctrl+W
Type "Berlin"
Sleep 4s
Enter
Sleep 4s
Down
Down
Down
Enter
Sleep 4s
Down
Down
Down
Down
Down
Down
Down
Down
Down
Enter
Sleep 4s
Down
Down
Down
Enter
Sleep 4s
Down
Enter
Sleep 4s
Down
Enter
Sleep 4s
Down
Down
Sleep 4s
Enter
Sleep 4s
Enter
Sleep 4s
Enter
Sleep 4s
Enter
Sleep 4s
Enter
Sleep 4s
Enter
Up
Enter
Sleep 4s
Type "Python Dev"
Sleep 4s
Enter
Sleep 15s





